### PR TITLE
RFC: immutable SpanContext

### PR DESCRIPTION
**Pull request by bensigelman**
Per the thread at https://github.com/opentracing/opentracing.github.io/issues/106

If we go forward with this, I will clean up the comments, etc.

### CODE REVIEW

**Comment by bensigelman** [comment]
The implementation implications are probably more interesting: https://github.com/opentracing/basictracer-go/pull/36

**Comment by yurishkuro** [comment]
@bensigelman mind if I commandeer this and basictracer PRs if you don't have time to finish them? I would like to use the new API before I merge TChannel-Go upgrade.

**Comment by bensigelman** [comment]
@yurishkuro I definitely don't mind... On the contrary, I am having personal queuing problems and appreciate the help.

**Comment by bensigelman** [comment]
(LGTM in its current state, btw)

**Comment by yurishkuro** [comment]
You mentioned some comments you wanted to change? I haven't looked at any, tbh.

**Comment by bensigelman** [comment]
@yurishkuro I wanted to scan all Tracer, Span, and SpanContext comments to look for mentions of baggage and SpanContext, then obviously just make sure everything still made sense.

**Comment by bensigelman** [comment]
(i.e., for all I know everything is in order... I just didn't check)

**Comment by yurishkuro** [comment]
I had a look, the comments seem ok, so merging. We can fix comments separately.

**Comment by peterbourgon** [comment]
This PR changed the public API, which broke Go kit.

**Pull request merged**
