### PR TITLE
Stop testing with Go 1.6

### PR DESCRIPTION
**Pull request by yurishkuro**
Mainly because Go 1.6 does not allow nested tests. Go 1.8 has been released already, do we need to be testing with more than two recent versions?

### CODE REVIEW

**Comment by gchaincl** [comment]
:+1:

**Comment by bhs** [comment]
Light googling failed to reveal the approximate distribution of Go versions in production... would be great to understand that before making this change. (I also wish it was possible to support different Go versions for tests and non-tests respectively)

**Comment by tedsuo** [comment]
In general, if we support a language version we should test with it. But in this particular case, I agree that the only thing we really need to test is if it still compiles in 1.6. 

If we're going to drop support for 1.6 that would help with a number of things, such as the `context` package mismatch it inflicts on us.

**Comment by tonyghita** [comment]
This should be merged before #176 can pass. @yurishkuro are you able to resolve the merge conflicts on this PR so we can move forward with the change?

**Pull request merged**
