### PR TITLE
Setup TravisCI

### PR DESCRIPTION
**Pull request by tschottdorf**

### CODE REVIEW

**Comment by yurishkuro** [comment]
lgtm

**Comment by yurishkuro** [comment]
@tschottdorf can we add a build badge to the top of readme?

**Comment by yurishkuro** [comment]
@tschottdorf looks like travis build failed https://travis-ci.org/opentracing/opentracing-go/builds/107015108, couldn't find go-vet

Also, what's the reason for doing this during build?
```
go get -d -t github.com/opentracing/opentracing-go/...
```

**Comment by bensigelman** [comment]
@yurishkuro, @tschottdorf added a dependency on a pretty-printing package from a test he wrote.

**Pull request merged**
