### PR TITLE
add the apparently-missing MIT license file

### PR DESCRIPTION
**Pull request by bensigelman**
Per https://github.com/opentracing/opentracing-go/issues/56

### CODE REVIEW

**Comment by yurishkuro** [comment]
:shipit:

**Comment by bensigelman** [comment]
I'll give people 48h to comment on this choice of license... I know there are some strong feelings out there. I am a when-in-Rome person with licenses, and I think MIT is the most prevalent for Go.

@yurishkuro @adriancole @slimsag have all said stuff about these topics before

**Comment by adriancole** [comment]
If go cannot be used without MIT (as core dependencies are licensed that
way), than another license (such as Apache) doesn't add value. So, sgtm

**Comment by tschottdorf** [comment]
:shipit:

**Comment by bensigelman** [comment]
48h :hourglass:

**Pull request merged**
